### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by ebbb** [rpearce11/xmlstats-nba-event-downloader#6]
Hi,

Tried to run your program and this happened:

```
$ python --version
Python 2.7.10

$ python main.py <token> <user-agent>
  File "main.py", line 37
SyntaxError: Non-ASCII character '\xe2' in file main.py on line 38, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by rpearce11** [comment]
Hi,

I had intended this to be python 3.5 only, and not invested effort into setting up on python 2.7.X.

I've placed that at the top of the readme, but perhaps I should do something different / better?

I could look at compatibility with 2.7.X or work out a why to install and enforce 3.5 - what are your thoughts?

Thanks

**Comment by ebbb** [comment]
Ahh, my mistake, sorry! Tried in Python 3.3 and it runs fine.
